### ISSUE TITLE
problem with linker script

### ISSUE THREAD

**Issue by JojoS62** [mbed-ce/mbed-ce-custom-targets#2]
I've tried to use my custom targets collection with mbed-ce:
https://github.com/JojoS62/custom_targets/tree/6.0.1
Trying with WEACT_F411CE:
- i have to include the custom_targets after mbed-os, other than in the example. Otherwise, I can not call mbed_setup_linker_script
- mbed-os tries to call mbed_setup_linker_script, but then the target is unknown

after changing the custom target to link against existing mbed_stm32f411xe, 
mbed_disable_mcu_target_file(mbed-stm32f411xe system_clock.c)
fails because mbed_ functions are not yet available at this time.

https://github.com/mbed-ce/mbed-ce-custom-targets/blob/dc633d6f986037ea17e88befcdb6d5a83e8828db/custom_targets/CMakeLists.txt#L62

as a workaround, it works when SetSysClock_PLL_HSE() and SetSysClock_PLL_HSI() are declared static, because these are only used internally. SetSysClock() is declared weak, so it gets overriden by the the custom system_clock.c.

**Comment by JojoS62** [comment]
correction:  mbed_disable_mcu_target_file(mbed-stm32l452xe system_clock.c)  is working, my mbed-ce master was not up to date.

Due to the weak declaration, it wouldn't be neccessary to remove it from the build, but it will save fllash space and so it seems to be the better solution.

**Comment by multiplemonomials** [comment]
So, is this good to be closed?

**Comment by JojoS62** [comment]
yes, but I want to check if it is not possible to include the custom targets after mbed-os. I see that in this case the raw_linker_script_path is empty, this could be ignored in case of custom target. Still testing.

**Comment by wdx04** [comment]
Do we have a generic solution to the linker script problem, when we don't have an existing target to link with?
